export = {
  average: require('./average'),
  chunk: require('./chunk'),
  compact: require('./compact'),
  clone: require('./clone'),
  get: require('./get'),
  hash: require('./hash'),
  identifier: require('./identifier'),
  max: require('./max'),
  min: require('./min'),
  omit: require('./omit'),
  pick: require('./pick'),
  random: require('./random'),
  randomString: require('./randomString'),
  roundTo: require('./roundTo'),
  sample: require('./sample'),
  shuffle: require('./shuffle'),
  sleep: require('./sleep'),
  slugify: require('./slugify'),
  sum: require('./sum'),
  unique: require('./unique')
}
